* _Making plots for the SISC paper_

This library contains some extra scripts that can be run to build
everything in this directory, run the different JMMs referenced in
the SISC paper, collect the results, and create Figures 8.1 and 8.2,
as well as Table 8.1. To do this, first set up the Python environment
by running:
#+BEGIN_SRC sh
$ pip install -r requirements.txt
#+END_SRC
from the root directory of the repository. Next, run:
#+BEGIN_SRC sh
$ ./run.sh
#+END_SRC
This script will build everything, collect the output, and make the
plots and tables. The intermediate data collected by the programs
will be written to files in `./data`, and the plots and tables will
be written to `./plots`.  

The usual README for this repository follows.

-----

* libjmm

  This is a C library implementing a variety of *jet marching methods*
  (JMMs) for solving the eikonal equation in 2D on a regular
  grid. Other JMMs for solving the eikonal equation on unstructured
  grids (triangle and tetrahedron meshes) and on structured grids in
  3D will be added later, as well as JMMs for solving other related
  equations.

  The library comes with a Python interface written using pybind11 and
  which is a straightforward mapping of the "object-oriented" C
  interface to an object-oriented Python library. All of the "classes"
  in the C library are exposed to make things transparent and simple.

** Compilation

   To compile, just run:
#+BEGIN_SRC sh
$ python setup.py install
#+END_SRC
   This will install a Python module named ~jmm~ which contains
   everything in a flat namespace.

** Tests

   To run the included unit tests, first install the module as
   described above, and then run:
#+BEGIN_SRC sh
$ python -m unittest
#+END_SRC
   This will in turn run the
   tests contained in each of the ~test_*.py~ files.

   Since the Python interface exposes exactly the same interface as
   the C library, we opt to just implement the tests using Python's
   unit testing facilities for simplicity and flexibility. These tests
   do double duty and make sure that the Python bindings are
   implemented correctly, and also that the library's implementation
   itself is correct.

** Tagged versions

   Some important versions are tagged (you can find these under the
   "branches" menu if you're browsing this repository using
   GitHub). Currently, there are the following branches:

   | Tag    | Description                                    |
   |--------+------------------------------------------------|
   | v0.1.1 | First version with ~eik~ working for s \neq 1. |
   | v0.1.0 | First version with ~eik~ working for s \equiv 1. |
